### ISSUE TITLE
Boot from SD card

### ISSUE THREAD

**Issue by mh1412** [OnionIoT/u-boot#5]
# Motivation

> Why are we doing this? What use cases does it support? What problems does it solve? What is the expected outcome?

Enable booting from SD card
Note: 
- Since SD card has built in wear-leveling management UBI is not needed here.
-  It is assumed user will always initialized SD card through a PC. All recovery mechanisms (web, tftp etc) do NOT need work for SD card.

# Description

> A clear and concise description of what you want to happen.
> It should be reasonably clear how the improvement would be implemented.

- Initialized SD card with firmware on a PC
- Set boot media to SD card in Omega uboot env
- Omega boots into OS from SD card
- During first boot omega should initialized rootfs on SD card

# Additional Resources

N/A

**Comment by greenbreakfast** [comment]
Work on booting from SD card has been iceboxed:
- When EXT4_FS support is enabled via kernel_menuconfig (add-sd-card-support is the base branch) - the kernel can't be decompressed during boot.
- More work is required - might be picked up later if this feature becomes a priority

All progress work available in [`feature/add-sd-card-support` branch](https://github.com/OnionIoT/u-boot/tree/feature/add-sd-card-support)
