### ISSUE TITLE
Adding UBI support for NAND Flash

### ISSUE THREAD

**Issue by mh1412** [OnionIoT/u-boot#6]
# Motivation

> Why are we doing this? What use cases does it support? What problems does it solve? What is the expected outcome?

Since NAND flash have limited write cycles, it is important to manage wear-leveling and bad blocks. 

# Description

> A clear and concise description of what you want to happen.
> It should be reasonably clear how the improvement would be implemented.

- omega is able to boot from NAND flash with UBI.
- u-boot is able to initialized NAND flash with UBI if none exist
- firmware recovery mechanisms (web, tftp, usb) should be able to work with NAND flash with UBI
- During boot Omega should be able to initialized rootfs on top of UBI. 

# Additional Resources

N/A

**Comment by greenbreakfast** [comment]
Support for UBI filesystem added in PR #8 
Firmware support added in https://github.com/OnionIoT/openwrt-buildsystem-wrapper/tree/feature/add-omega3
